services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic
    ports:
      - '3000:3000'
    container_name: go-web
    environment:
      - MARIADB_10_4_DRUPAL_USERNAME=drupal
      - MARIADB_10_4_DRUPAL_PASSWORD=drupal
      - MARIADB_10_4_DRUPAL_DATABASE=drupal
      - POSTGRES_SECURE_USERNAME=secure
      - POSTGRES_SECURE_PASSWORD=secure
      - POSTGRES_SECURE_DATABASE=secure
      - POSTGRES_SECURE_HOST=postgres-secure
      - POSTGRES_SECURE_PORT=5432

  mariadb-10-4-drupal:
    image: uselagoon/mariadb-10.4-drupal
    labels:
      lagoon.type: mariadb-single
    ports:
      - '3306'
    environment:
      - LAGOON_TEST_VAR=test
      - LAGOON_GIT_SHA=SHA256
      - LAGOON_ENVIRONMENT_TYPE=development

  mongo-somedb:
    image: uselagoon/mongo-4:latest
    labels:
      lagoon.type: mongo
    ports:
      - '27017'

  postgres-secure:
    image: testlagoon/postgres-15:main
    labels:
      lagoon.type: postgres
    ports:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=secure
      - POSTGRES_USER=secure
      - POSTGRES_DB=secure
