volumes:
  redis-5-data:
  solr-7-data:
  solr-8-data:
  elasticsearch-6-data:
  scratch:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic-persistent
      lagoon.persistent: /app/files
      lagoon.persistent.size: 10Mi
      lagoon.persistent.class: bulk
    ports:
      - '3003:3000'
    container_name: go-web
    environment:
      - LAGOON_TEST_VAR=internal-services-test
      - LAGOON_GIT_SHA=SHA256
      - LAGOON_ENVIRONMENT_TYPE=development
      - STORAGE_LOCATION=/app/files
    volumes:
      - scratch:/app/files
      - ./docker-compose.yml:/app/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock

  mariadb-10-2:
    image: amazeeio/mariadb:v0.21.0
    labels:
      lagoon.type: mariadb-single
      lagoon.persistent.size: 100Mi
    ports:
      - '3306'

  mariadb-10-g:
    image: amazeeio/mariadb-galera:latest
    labels:
      lagoon.type: mariadb-single
    ports:
      - '3306'

  postgres-12:
    image: uselagoon/postgres-12:latest
    labels:
      lagoon.type: postgres-single
      lagoon.persistent.size: 100Mi
    ports:
      - '5432'

  postgres-16:
    image: uselagoon/postgres-16:latest
    labels:
      lagoon.type: postgres
    ports:
      - '5432'

  mysql-8-4:
    image: amazeeio/mysql:8.4-24.6.0
    labels:
      lagoon.type: mariadb-single
    ports:
      - "3306"

  elasticsearch-6:
    image: amazeeio/elasticsearch:6-latest
    environment:
    - cluster.name=elasticsearch-cluster
    - bootstrap.memory_lock=true
    - "ELASTICSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-6-data:/usr/share/elasticsearch/data
    labels:
      lagoon.type: elasticsearch
      lagoon.persistent.size: 100Mi
    ports:
      - '9200'

  mongo-4:
    image: amazeeio/mongo:4
    labels:
      lagoon.type: mongo
    ports:
      - '27017'

  redis-5:
    image: amazeeio/redis-persistent:latest
    labels:
      lagoon.type: redis-persistent
      lagoon.persistent.size: 100Mi
    ports:
      - '6379'
    volumes:
      - redis-5-data:/data

  redis-6:
    image: amazeeio/redis:6
    labels:
      lagoon.type: redis
    ports:
      - '6379'

  solr-7:
    image: amazeeio/solr:7-21.10.0
    labels:
      lagoon.type: solr
      lagoon.persistent.size: 100Mi
    ports:
     - "8983"
    volumes:
      - solr-7-data:/var/solr
    command:
      - solr-precreate
      - mycore

  solr-8:
    image: amazeeio/solr:8-21.12.0
    labels:
      lagoon.type: solr
      lagoon.persistent.size: 100Mi
    ports:
     - "8983"
    volumes:
      - solr-8-data:/var/solr
    command:
      - solr-precreate
      - mycore
