version: '2'

volumes:
  solrData:
  solrData7:
  opensearch-data1:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic
    ports:
      - '3000:3000'
    container_name: go-web
    environment:
      - LAGOON_TEST_VAR=test
      - LAGOON_GIT_SHA=SHA256
      - LAGOON_ENV=Prod
      
  mariadb-10-4:
    image: uselagoon/mariadb-10.4
    labels:
      lagoon.type: mariadb-single
    ports:
      - '3306'
  
  mariadb-10-5:
    image: uselagoon/mariadb-10.5
    labels:
      lagoon.type: mariadb-single
    ports:
      - '3306'

  mariadb-10-6:
    image: uselagoon/mariadb-10.6
    labels:
      lagoon.type: mariadb
    ports:
      - '3306'

  mongo-4:
    image: uselagoon/mongo:latest
    labels:
      lagoon.type: mongo
    ports:
      - '27017'

  opensearch-2:
    image: uselagoon/opensearch-2:latest
    environment:
    - cluster.name=opensearch-cluster
    - node.name=opensearch
    - discovery.seed_hosts=opensearch
    - cluster.initial_cluster_manager_nodes=opensearch
    - bootstrap.memory_lock=true
    - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    labels:
      lagoon.type: opensearch
    ports:
      - '9200'

  postgres-11:
    image: uselagoon/postgres-11
    labels:
      lagoon.type: postgres-single
    ports:
      - '5432'

  postgres-12:
    image: uselagoon/postgres-12
    labels:
      lagoon.type: postgres-single
    ports:
      - '5432'

  postgres-13:
    image: uselagoon/postgres-13
    labels:
      lagoon.type: postgres-single
    ports:
      - '5432'

  postgres-14:
    image: uselagoon/postgres-14
    labels:
      lagoon.type: postgres
    ports:
      - '5432'

  redis-5:
    image: uselagoon/redis-5
    labels:
      lagoon.type: redis
    ports:
      - '6379'

  redis-6:
    image: uselagoon/redis-6
    labels:
      lagoon.type: redis
    ports:
      - '6379'

  solr-7:
    image: uselagoon/solr-7
    labels:
      lagoon.type: solr
    ports:
     - "8983"
    volumes:
      - solrData7:/var/solr
    command:
      - solr-precreate
      - mycore

  solr-8:
    image: uselagoon/solr-8
    labels:
      lagoon.type: solr
    ports:
     - "8983"
    volumes:
      - solrData:/var/solr
    command:
      - solr-precreate
      - mycore

